[build]
# Set the default target to match the Cortex-M0+ in the RP2040
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [

    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    ]

runner = "picotool load --update --verify --execute -t elf"

